version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: llmfixu-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    networks:
      - llmfixu-network

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: llmfixu-openwebui
    ports:
      - "3000:8080"
    volumes:
      - openwebui_data:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=your-secret-key-change-this
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - llmfixu-network

  chromadb:
    image: chromadb/chroma:latest
    container_name: llmfixu-chromadb
    ports:
      - "8000:8000"
    volumes:
      - chromadb_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    restart: unless-stopped
    networks:
      - llmfixu-network

  n8n:
    image: n8nio/n8n:latest
    container_name: llmfixu-n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=changeme
      - WEBHOOK_URL=http://localhost:5678/
    restart: unless-stopped
    networks:
      - llmfixu-network

volumes:
  ollama_data:
  openwebui_data:
  chromadb_data:
  n8n_data:

networks:
  llmfixu-network:
    driver: bridge